// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  test: {
    schema: "prisma/test.schema.prisma",
    datasource: {
      url: "file:./prisma/dev.db",
    },
  },
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["POSTGRES_URL"],
  },
});
